
import 'package:hive_ce/hive.dart';

part 'person_model.g.dart';
// This file is auto generated by running command:
// flutter packages pub run build_runner build
// part 'modelname.g.dart'; (Replace "modelname" with your model name)

@HiveType(typeId: 0)
class Person extends HiveObject {
  // @HiveType tells Hive this class is a Hive model.
  // typeId: 0 uniquely identifies this class inside your app. Must be unique.
  // Changing it after data is saved will break the database unless migrated.

  // extends HiveObject gives you helper methods like:
  // save() → update entry
  // delete() → delete entry
  // access to key

  // If there are multiple hive models like Income, Expense, Family and so on.
  // Then each hive model will have unique typeId. 
  // Example:
  // Income -> typeId: 0
  // Expense -> typeId: 1
  // Family -> typeId: 2
  

  @HiveField(0)
  final String name;
  // Hive stores your object as binary data.
  // HiveField(n) gives each field a position so Hive knows how to encode/decode it.

  @HiveField(1)
  final int age;

  @HiveField(2)
  final String contactNumber;

  @HiveField(3)
  final DateTime dateTime;

  Person({ // Constructor
    required this.name,
    required this.age,
    required this.contactNumber,
    required this.dateTime,
  });
}
